### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by ammendola** [PaulFelz/WPM_9_1#1]
Dies ist ein Test issue. Ist es? Ja!

Die Gliederung sieht soweit doch ganz vernünftig aus. Bin gespannt, mit welchen Inhalten Du sie füllst. Dann bekommst Du auch ein richtiges issue.

Viele Grüße
Andrea

**Comment by ammendola** [comment]
Ich habe mir erlaubt, deine Watch-Funktion zu aktivieren. Vielleicht bekommst Du ja per Mail Nachricht über diesen Kommentar. Dann hätte es funktioniert.

Schau mal in meinen Text. Ist schon einiges drin zum Lesen.

Viele Grüße
Tandempartner

**Comment by ammendola** [comment]
Ein Versehen. Ticket ist wieder geöffnet.

**Comment by PaulFelz** [comment]
Kein Thema, wird nun geschlossen :)
