### ISSUE TITLE
Kleine Formalia

### ISSUE THREAD

**Issue by ammendola** [PaulFelz/WPM_9_1#4]
Lieber Paul,

hier nun ein kleines issue mit drei kleinen formalen Dingen, die mir noch aufgefallen sind (die Korrekturen habe ich jeweils fett markiert):

1. Kap. 1.1: ...kann davon ausgegangen werden, das**s** ein Großteil der bereitgestellten Coverbilder von Amazon ist.

2. Kap. 2: ...u.v.m**.**

3. Kap. 2: müsste das Wort übertakten nicht groß geschrieben werden? Schließlich benutzt Du es ja hier als Verbalsubstantiv, richtig? Also das **Übertakten**

Das war' schon. Zwei weitere, nun mehr inhaltliche issues folgen sogleich.

Viele Grüße
Andrea

**Comment by ammendola** [comment]
Hallo Tandempartner,

wäre das für dich in Ordnung, wenn ich am nächsten Montag, (dann bin ich nämlich noch in Münster) einen letzten Pull Request zu deinem Text mache, um noch Dinge, dir mir auffallen, zu korrigieren? Dann könntest Du noch in Ruhe am Wochenende was an Deinem Text machen, so denn überhaupt nötig, und Du hättest ja am Montag und Dienstag noch Zeit, dir den Pull Request anzuschauen.

OK?

Dein Tandempartner

**Comment by PaulFelz** [comment]
Ja klar!
Du darfst mir gern noch ein Pull Request schicken.

Wie gesagt bin ich immer gern bereit zu lernen. Aber ja bitte erst Montag, ich hoffe dann fällt dir nur noch sehr wenig auf. Denn Rechtschreibung und auch die kleinen Formalia von oben mache ich die nächsten tage fertig. Aber du hast so ein gutes Auge, sehr gern kannst du dann noch mal "Pull Requesten" :tada:  Mein Text wird nur noch besser :factory: 

Viele Grüße
paul

**Comment by ammendola** [comment]
Super, dann setze ich mich Montag dran. Falls bis dahin aber alles korrigiert sein sollte, spare ich mir den Pull Request. Ich geb Dir aber auf jeden Fall Bescheid!

Viele Grüße
Andrea

**Comment by PaulFelz** [comment]
Danke für deine Hinweise, auch Formalia sind nun ausgebessert.
Mache am Wochenende noch einen letzten Check unserer beiden Texte, denke bei dir dürfte aber alles korrekt sein und ich hoffe auch das du am Montag kein Request mehr schreiben brauchst. :yum: 

VG
paul

**Comment by ammendola** [comment]
Alles klar, so machen wir es, Tandempartner!

VG
A.
