### ISSUE TITLE
Wer hat worauf Zugriff und wieso?

### ISSUE THREAD

**Issue by ammendola** [PaulFelz/WPM_9_1#5]
Servus Paul,

in Kapitel 1.3 schreibst Du, dass einige Abteilungen nur auf ihre jeweiligen Laufwerke Zugriff haben. Ich habe mich hier gefragt, wieso gerade diese Abteilungen nur auf ihre eigenen Laufwerke Zugriff haben. Haben diese Abteilungen besonders sensible Daten, die kein anderer sehen darf? Und wenn das stimmt, haben dann die anderen Abteilungen, die Du hier nicht nennst,  Zugriff auf alle Partitionen, also etwa auch Zugriff auf die von Dir genannten Abteilungen? Haben diese anderen Abteilungen keine schützenswerten Daten?

Ich hoffe, ich habe mich einigermaßen verständlich gemacht. Ich hatte von Beginn an etwas Probleme, das genaue Rechtemanagement zu verstehen. Das lässt sich aber sicher schnell mit ein paar erklärenden Nebensätzen auflösen.

Beste Grüße
Andrea

**Comment by PaulFelz** [comment]
Danke für den Hinweis, habe das falsche Vokabular benutzt. Es heißt nicht Abteilungen sondern Organisationseinheiten. Das Referat teilt sich in Organisationseinheiten auf und die Organisationseinheiten haben jeweils eine Partition auf dem Netzlaufwerk und innerhalb der Partition haben die Abteilungen der Organisationseinheit Zugriff auf alle Ordner auf der Partition.
Hoffe es ist nun richtig und damit verständlich.

VG

**Comment by ammendola** [comment]
Ja, wunderbar. Jetzt ist es absolut klar. Gerade bei einer solchen hierarchischen Struktur braucht es ein klares Vokabular, aber das ist ja jetzt so. Perfekt! Ich schließe dann mal das issue, wenn's recht ist.

VG
A.
