### ISSUE TITLE
Datendurchsatz und Übertakten

### ISSUE THREAD

**Issue by ammendola** [PaulFelz/WPM_9_1#6]
Hallo Paul,

nun noch zwei Fragen zu Kap. 2:

1. Hier schreibst Du, dass der Datendurchsatz stimmen muss, da ansonsten die Sicherung zu lange dauern könnte. Kannst Du hier vielleicht noch ein paar Zahlen nennen? Gibt es irgendwelche Datendurchsatzgrenzen, die vielleicht voreingestellt sind? Oder müsst ihr das jeweils manuell prüfen und ggf. das Backup stoppen?

2. Auch wenn du das Übertakten sehr schön verlinkt hast und man die Erklärung, was das genau ist, über diesen Link bekommt, habe ich ein bisschen vermisst, welche Risiken das genau sind, die beim Übertakten entstehen. Vor allem, weil Du dann schreibst, dass das ein Know-How erfordert, das nicht vorhanden ist. Und spätestens hier wäre es gut zu wissen, was das für ein Know-How ist, was man braucht, um ein Übertakten zu verhindern.

Beide Fragen lassen sich auch hier bestimmt schnell durch ein paar Erläuterungen erklären.

Das war es nun von meiner Seite mit formalen und inhaltlichen Anmerkungen zu Deinem sehr schön gelungenen Text. Glückwunsch, Partner!

Wir lesen uns!
Andrea

**Comment by PaulFelz** [comment]
Heyhey, ich habs mal in meinen Text eingesetzt, dadurch wird er vielleicht noch ein wenig runder :)

**Comment by ammendola** [comment]
Heyho,

 

ja, das ist jetzt viel runder und jetzt ist auf jeden Fall klar, was das für Risiken sind. Schau vielleicht nochmal, es hat sich jetzt doch der ein oder andere Flüchtigkeitsfehler in den neuen Text eingeschlichen…

 

Viele Grüße!

Andrea

 

 

Von: PaulFelz <notifications@github.com> 
Gesendet: Montag, 13. Mai 2019 13:51
An: PaulFelz/WPM_9_1 <WPM_9_1@noreply.github.com>
Cc: ammendola <ammendola@uni-muenster.de>; Author <author@noreply.github.com>
Betreff: Re: [PaulFelz/WPM_9_1] Datendurchsatz und Übertakten (#6)

 

Heyhey, ich habs mal in meinen Text eingesetzt, dadurch wird er vielleicht noch ein wenig runder :)

**Comment by PaulFelz** [comment]
Ups, das Ticket zu früh geschlossen ^^ 
Ja danke, ich prüfe! War ja klar das sich dann wieder was einschleicht

VG
