### ISSUE TITLE
Letzte Korrekturen

### ISSUE THREAD

**Issue by ammendola** [PaulFelz/WPM_9_1#7]
Hallo Paul,

erst wollte ich gerade doch einen kleinen pull request machen, aber dann ist was interessantes passiert: Denn als ich Korrekturen eingeben wollte, die in deiner jetzigen Version sah, waren diese in der Pull Request-Version nicht mehr vorhanden. Etwas merkwürdig, also habe ich den Pull Request wieder gelöscht und schreibe dir die paar Dinge, die mir noch aufgefallen sind, hier im Ticket. Sind eh nicht mehr viel (die Änderungen habe ich wieder fett markiert):

--------------------------------------------------------------------------------------------------------------------
Kap. 1.3:

"Herauszustellen ist noch, dass das Referat aus 5 Organisationseinheiten besteht**:** Querschnittmanagement..."

"Das bedeutet**: D**ie Organisationseinheiten..."

Kap. 2:

"...da die Performance unter Umständen hier**für** nicht ausreicht. Wenn **man** sich die technischen Daten bspw. eines Einplatinencomputers wie der Raspberry Pi 3B **anschaut**, ist festzuhalten, dass auch ein solch aktuelles Modell nur einen Datendurchsatz von 38,5 Mbit/s hat. Hierbei ist die Berechnung wie folgt**:** **E**ine **große Datenm**enge [dies würde ich streichen: an Daten, wie oben angegeben,] von 500GB muss als Backup gesichert werden. Wenn 38,5 Mbit/s gesichert werden, dann sind das umgerechnet pro Sekunde 4,812 MByte. 500GB zu sichernde Daten sind umgerechnet 500.000 Mbyte. Also dauert das sichern von 500.000 Mbyte bei einem Datendurchsatz von 4,812 Mbyte**/s** [würde ich streichen bzw. abkürzen: pro Sekunde] **(**auf volle Sekunden aufgerundet**)** 103.907 Sekunden**,** **i**n Stunden sind es ca. 28,86 [würde ich streichen: Stunden].

--------------------------------------------------------------------------------------------------------------------

Es war ein bisschen schwer, meine Korrekturvorschläge hier in den issue reinzupacken, aber ich hoffe, es wird klar, was ich meine. Wenn ich zu kleinkariert gewesen sein sollte, dann bitte mir sagen oder die Vorschläge einfach ignorieren.

Wir sehen uns am Donnerstag!

Beste Grüße
A.

**Comment by PaulFelz** [comment]
Nö, sieht gut aus :), verstehe ich und ist noch das Sahnehäubchen auf dem i-Tüpfelchen ;D
Ich schau mal morgen, zur Korrektur :)

**Comment by PaulFelz** [comment]
Korrigiert, nur im zweiten Kapitel; wollte ich nun nicht deinen Vorschlag annehmen. Ich bin kein Freund von "man" in Texten und versuche diese Schreibweise eher zu vermeiden. 
Du hattest angemerkt: 
>Wenn **man** sich die technischen Daten bspw. eines Einplatinencomputers wie der Raspberry Pi 3B anschaut, ist festzuhalten, dass auch ein solch aktuelles Modell nur einen Datendurchsatz von 38,5 Mbit/s hat. 

Ich habs jetzt so verbessert: 
>Wenn sich die technischen Daten bspw. eines Einplatinencomputers wie der Raspberry Pi 3B angesehen werden, ist festzuhalten, dass auch ein solch aktuelles Modell nur einen Datendurchsatz von 38,5 Mbit/s hat. 

Ansonsten Danke für all die vielen anderen wertvollen Tipps und deine Korrekturen, die haben mir sehr geholfen! Einiges gelernt! :100:

**Comment by ammendola** [comment]
Hey Partner,

ja na klar, ist alles ok so. Es war wirklich nur ein Vorschlag und so ist es absolut ok. War ohnehin nur eine Frage des Geschmacks, die ich gar nicht hätte anmerken müssen.

Jetzt sind wir wohl beide fertig. Ich bin jedenfalls durch und freue mich auf Donnerstag!
A,
